config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    root 'companies#index'  
	resources :companies
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/company.rb
class Company < ApplicationRecord
	 validates :name, presence: true
	 validates :address, presence: true
	 validates :register_number, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
	def index
		@companies=Company.all

	end
	
	def new
		@company=Company.new
	end

	def create
		@companies=Company.new(company_params)
		if @companies.save
			flash[:success] = "Successfully Created!"
			redirect_to companies_path
	    else
	    	flash[:error] = "Sorry! Could not complete the request, please try again!"
           render :action =>'new'
	    end	
	end
    
     def show
     	@company=Company.find(params[:id])
     end 
	def edit
		@company=Company.find(params[:id])
	end

	def update
		@company=Company.find(params[:id])
		if @company.update_attributes(company_params)
			flash[:success] = "Successfully Updated!"
           redirect_to companies_path
		else
			flash[:error] = "Sorry! Could not complete the request, please try again!"
			render :action => 'edit'
		end	
	end

	def destroy
		if Company.find(params[:id]).destroy
            flash[:success] = "Successfully Deleted!"            
			redirect_to companies_path
		else
			flash[:error] = "Sorry! Could not complete the request, please try again!"
		    redirect_to companies_path
		end   	
	end


	private

		def company_params
      		params.require(:company).permit(:name,:address,:register_number)	
   		 end 
end

app/controllers/home_routes_controller.rb
class HomeRoutesController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/home_routes_helper.rb
module HomeRoutesHelper
end

app/views/companies/index.html.erb
<span>Company Details</span>
<%= link_to "New Company", new_company_path, :class => "btn btn-primary btn-new " %>
<ol>
  <li>3</li>
  <li>3</li>
  <li>3</li>
  <li>3</li>
  <li>3</li>
  <li>3</li>
  <li>3</li>
</ol>

app/views/companies/new.html.erb
<div class="row">
                <div class="col-lg-12">
                    <div class="ibox">
                        <div class="ibox-title">
                            <center><h2>Create New Companies</h2></center>
                            
                        </div>
                        <div class="ibox-content">
                        
                        		<%= form_for @company, url: {action: "create"}, html: {class: 'wizard-big'} do |role| %>
                            
                                <fieldset>
                                   
								 <%@company.errors.full_messages.each do |msg|%>
									<p style ="color : red"><%= msg %></p>
                                      <%end%>
                                    <div class="row">
                                        <div class="col-lg-8">
                                            <div class="form-group">
                                            <br>
                                            <%=role.label :name,"name"%>
											<%= role.text_field :name, :class=>"form-control", :placeholder => "Enter name", :required => "true" %>
											</div>
                                             <div class="form-group">
                                            <br>
                                            <%=role.label :address,"address "%>
                                            <%= role.text_field :address, :class=>"form-control", :placeholder => "Enter address", :required => "true" %>
                                            </div>	
                                            <div class="form-group">
                                            <br>
                                            <%=role.label :register_number,"register_number "%>
                                            <%= role.text_field :register_number, :class=>"form-control", :placeholder => "Enter register_number", :required => "true" %>
                                            </div>																 
										    <div class="form-group text-center">
                                          <%= role.submit "Create Company", :class=>"btn btn-primary"  %>
					                      </div>
                                        </div>
                                        </div>
                                        <%end%>
                                    </fieldset>
                             </form>
                            
                          </div>
                    </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CompanyApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>